[package]
name = "chatwarp-api"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
axum = { version = "0.7.9", features = ["http2", "multipart", "ws"] }
axum-server = { version = "0.7.1", features = ["tls-rustls"] }
base64 = "0.22.1"
dotenvy = "0.15.7"
futures = "0.3.31"
http = "1.2.0"
hyper = { version = "1.5.2", features = ["full"] }
mime_guess = "2.0.5"
lapin = { version = "2.5.0", features = ["rustls", "rustls-native-certs"] }
prost = "0.13.4"
reqwest = { version = "0.12.12", default-features = false, features = ["json", "rustls-tls"] }
rustls-pemfile = "2.2.0"
sentry = { version = "0.36.0", default-features = false, features = ["reqwest", "rustls"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
sqlx = { version = "0.8.3", default-features = false, features = ["runtime-tokio-rustls", "postgres", "macros"] }
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "signal", "net", "sync", "time", "fs"] }
tokio-rustls = "0.26.1"
tonic = { version = "0.12.3", features = ["transport"] }
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["cors", "trace", "compression-full", "limit", "fs"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt", "json"] }
uuid = { version = "1.12.1", features = ["v4", "serde"] }

[build-dependencies]
protoc-bin-vendored = "3.1.0"
tonic-build = "0.12.3"

[dev-dependencies]
tower = { version = "0.5.2", features = ["util"] }
